### PR TITLE
Alternate evalops

### PR DESCRIPTION
**Pull request by leissa**
Let's discuss any remaining issues here.

Over the weekend I'll try out this lambda lifting during PE. This should improve several issues.

### CODE REVIEW

**Comment by richardmembarth** [comment]
The only remaining issue I see at the moment is #48 (apart from the lambda lifting thing).

**Comment by richardmembarth** [comment]
Check if this is correct: AnyDSL/impala@13ef0f9

**Comment by leissa** [comment]
done cleanup: AnyDSL/impala@c47c36d9

**Comment by leissa** [comment]
Fixed issue #48. Can we merge then?

**Pull request merged**
