### PR TITLE
Debug support

### PR DESCRIPTION
**Pull request by richardmembarth**
- add location information to nodes in thorin
- emit basic debug information (currently line info only)
- set -g flag by CMake

### CODE REVIEW

**Comment by leissa** [comment]
For the most part, this patch looks pretty straight-forward.
I just have three remarks:

* Where is the `loc` actually glued into the llvm-IR?
* Maybe we should add a default location as default argument in World.
* Is there anything I missed which is open to debate or more complicated?

**Comment by richardmembarth** [comment]
* The loc is set [here](https://github.com/AnyDSL/thorin/commit/efb6b50273ba116441e54dd9eaaff3f8383b07af#diff-89f9f92c37df2e05e09bffb9221adfbaR245). This is done for primops only atm.
* There is nothing more complicated, we do not emit debug information for variables atm, this is still missing.

**Comment by leissa** [comment]
ah ok, missed that line.

**Comment by leissa** [comment]
Then we should merge.

**Comment by richardmembarth** [comment]
Removed assert from DefNode since we use the Location() default constructor now.

**Pull request merged**
