### PR TITLE
Mem2reg

### PR DESCRIPTION
**Pull request by leissa**
removes SSA construction stuff and just relies on the ```resolve_loads```.

### CODE REVIEW

**Comment by leissa** [comment]
Ah, i see. That was a tough one. A miracle that this problem didn't pop up earlier :)

**Comment by leissa** [comment]
Can you give the ```dead_load_opt``` another shot on your code?

**Comment by madmann91** [comment]
Everything seems to work but there are still moderate/severe performance regressions for GPU code. I am looking into this.

**Comment by madmann91** [comment]
Merged.

**Pull request merged**
